ssss

diff --git a/.github/workflows/pipeline1.yml b/.github/workflows/pipeline1.yml
--- a/.github/workflows/pipeline1.yml
+++ b/.github/workflows/pipeline1.yml
@@ -22,7 +22,7 @@ env:
   api_product: Cicd-Prod-Product
   developer: hr@api.com
   app: hrapp
-  NEWMAN_TARGET_URL: NoTargetProxy_GET_Req_Pass_New.postman_collection.json
+  NEWMAN_TARGET_URL: NoTargetProxy_GET_Req_Pass_SAML.postman_collection.json
   LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
   ZAP_TARGET_API_URL: https://rimshaaizaz-eval-prod.apigee.net/notargetproxy
   
@@ -97,8 +97,8 @@ jobs:
    Deployment:
     runs-on: ubuntu-latest
     # needs: Pre-Deployment
-    # outputs:
-      # output1: ${{ steps.step1.outputs.stable_revision_number }}
+    outputs:
+      output1: ${{ steps.step1.outputs.stable_revision_number }}
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
@@ -107,10 +107,10 @@ jobs:
        run: bash ./apigee-cicd-master/scripts/revision.sh
        shell: bash
       
-     # - name: Echo Current Stable Revision
-       # id: step1
-       # run: echo "::set-output name=stable_revision_number::$stable_revision_number"
-       # # run: echo "stable_revision_number=$stable_revision_number"
+     - name: Echo Current Stable Revision
+       id: step1
+       run: echo "::set-output name=stable_revision_number::$stable_revision_number"
+       # run: echo "stable_revision_number=$stable_revision_number"
       
      # - name: Install fixed Maven Plugin
        # run: mvn install -f ${{ github.workspace }}/apigee-config-maven-plugin-master/pom.xml
@@ -122,93 +122,93 @@ jobs:
      - name: Deploy Proxy
        run: mvn clean install -f ${{ github.workspace }}/apigee-cicd-master/${{ env.ProxyName }}/pom.xml -Psandbox -Dusername=apigee.cicduser1@maf.ae -Dpassword=cicduser$ -Dorg=${{ env.ORG }} -Dapigee.config.options=update -Dapigee.app.ignoreAPIProducts=true 
        
-     # - name: commit-status-update
-       # uses: ouzi-dev/commit-status-updater@v1.1.0
-       # continue-on-error: true
-       # if: always()
-       # with:
-        # status: "${{ job.status }}"
-        # addHoldComment: "true"
-        # pendingComment: "Deployment stage pending!"
-        # successComment: "Deployment stage succeeded!"
-        # failComment: "Deployment stage failed!"
+     - name: commit-status-update
+       uses: ouzi-dev/commit-status-updater@v1.1.0
+       continue-on-error: true
+       if: always()
+       with:
+        status: "${{ job.status }}"
+        addHoldComment: "true"
+        pendingComment: "Deployment stage pending!"
+        successComment: "Deployment stage succeeded!"
+        failComment: "Deployment stage failed!"
         
-     # - name: Microsoft Teams Notification
-       # uses: skitionek/notify-microsoft-teams@master
-       # if: always()
-       # with:
-        # webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
-        # needs: ${{ toJson(needs) }}
-        # job: ${{ toJson(job) }}
-        # steps: ${{ toJson(steps) }} 
+     - name: Microsoft Teams Notification
+       uses: skitionek/notify-microsoft-teams@master
+       if: always()
+       with:
+        webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
+        needs: ${{ toJson(needs) }}
+        job: ${{ toJson(job) }}
+        steps: ${{ toJson(steps) }} 
    
-   # Post-Deployment:
-    # runs-on: ubuntu-latest
-    # needs: Deployment
-    # steps:
-     # - name: Checkout Repository
-       # uses: actions/checkout@v2
+   Post-Deployment:
+    runs-on: ubuntu-latest
+    needs: Deployment
+    steps:
+     - name: Checkout Repository
+       uses: actions/checkout@v2
        
-     # - name: Echo Output  
-       # run: echo "stable_revision_number=${{needs.Deployment.outputs.output1}}" >> $GITHUB_ENV 
+     - name: Echo Output  
+       run: echo "stable_revision_number=${{needs.Deployment.outputs.output1}}" >> $GITHUB_ENV 
        
-     # # - name: Install fixed Maven Plugin
-       # # run: mvn install -f ${{ github.workspace }}/apigee-config-maven-plugin-master/pom.xml
+     # - name: Install fixed Maven Plugin
+       # run: mvn install -f ${{ github.workspace }}/apigee-config-maven-plugin-master/pom.xml
        
-     # - name: Integration Test through script file
-       # id: integration
-       # run: bash ./apigee-cicd-master/scripts/integration.sh
-       # shell: bash
-       # continue-on-error: true
+     - name: Integration Test through script file
+       id: integration
+       run: bash ./apigee-cicd-master/scripts/integration.sh
+       shell: bash
+       continue-on-error: true
        
-     # - name: Publishing Newman Integration Report to Artifacts
-       # uses: actions/upload-artifact@v2
-       # if: always()
-       # with:
-        # name: Newman Integration Report
-        # path: ${{ github.workspace }}/reports/newman_report.html
+     - name: Publishing Newman Integration Report to Artifacts
+       uses: actions/upload-artifact@v2
+       if: always()
+       with:
+        name: Newman Integration Report
+        path: ${{ github.workspace }}/reports/newman_report.html
        
-     # - name: ZAP Scan
-       # if: steps.integration.outcome == 'success'
-       # id: ZAP
-       # continue-on-error: true
-       # uses: zaproxy/action-api-scan@v0.1.0
-       # with:
-          # token: ${{ secrets.GITHUB_TOKEN }}
-          # docker_name: 'owasp/zap2docker-stable'
-          # format: openapi
-          # target: '${{ env.ZAP_TARGET_API_URL }}'
-          # cmd_options: '-z "-configFile /zap/wrk/apigee-cicd-master/zap/options.prop"'
-          # #fail_action: true
+     - name: ZAP Scan
+       if: steps.integration.outcome == 'success'
+       id: ZAP
+       continue-on-error: true
+       uses: zaproxy/action-api-scan@v0.1.0
+       with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          docker_name: 'owasp/zap2docker-stable'
+          format: openapi
+          target: '${{ env.ZAP_TARGET_API_URL }}'
+          cmd_options: '-z "-configFile /zap/wrk/apigee-cicd-master/zap/options.prop"'
+          #fail_action: true
        
-     # - name: Undeploy Current & redeploy stable revision
-       # if: steps.integration.outcome == 'failure' || steps.ZAP.outcome == 'failure'
-       # id: undeploy
-       # run: bash ./apigee-cicd-master/scripts/undeploy.sh
-       # shell: bash
+     - name: Undeploy Current & redeploy stable revision
+       if: steps.integration.outcome == 'failure' || steps.ZAP.outcome == 'failure'
+       id: undeploy
+       run: bash ./apigee-cicd-master/scripts/undeploy.sh
+       shell: bash
 
-     # - name: Undeploy Check
-       # if: steps.undeploy.outcome == 'success'
-       # run: |
-        # echo "Integration/ZAP test Failed. Failing the Job!"
-        # exit 1
+     - name: Undeploy Check
+       if: steps.undeploy.outcome == 'success'
+       run: |
+        echo "Integration/ZAP test Failed. Failing the Job!"
+        exit 1
        
-     # - name: commit-status-update
-       # uses: ouzi-dev/commit-status-updater@v1.1.0
-       # continue-on-error: true
-       # if: always()
-       # with:
-        # status: "${{ job.status }}"
-        # addHoldComment: "true"
-        # pendingComment: "Post-Deployment stage pending!"
-        # successComment: "Post-Deployment stage succeeded!"
-        # failComment: "Post-Deployment stage failed!"
+     - name: commit-status-update
+       uses: ouzi-dev/commit-status-updater@v1.1.0
+       continue-on-error: true
+       if: always()
+       with:
+        status: "${{ job.status }}"
+        addHoldComment: "true"
+        pendingComment: "Post-Deployment stage pending!"
+        successComment: "Post-Deployment stage succeeded!"
+        failComment: "Post-Deployment stage failed!"
      
-     # - name: Microsoft Teams Notification
-       # uses: skitionek/notify-microsoft-teams@master
-       # if: always()
-       # with:
-        # webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
-        # needs: ${{ toJson(needs) }}
-        # job: ${{ toJson(job) }}
-        # steps: ${{ toJson(steps) }}
+     - name: Microsoft Teams Notification
+       uses: skitionek/notify-microsoft-teams@master
+       if: always()
+       with:
+        webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
+        needs: ${{ toJson(needs) }}
+        job: ${{ toJson(job) }}
+        steps: ${{ toJson(steps) }}
